### ISSUE TITLE
Issues on slow internet or google sheet is busy.

### ISSUE THREAD

**Issue by seccpur** [telerik/Android-samples#32]
The example codes  in this repository works fine on normal internet speed but application crashes on slow internet or while trying to call downloadUrl() when the google sheet is still updating. Any help? 
It is advised to check if the final JSONObject is null or not?
Thanks.

**Comment by LanceMcCarthy** [comment]
Hi @seccpur, 

This repository contains example for UI for Android, which was deprecated in 2016. We no longer provide updates for the code examples within.

Your question seems to be more relevant for general Java/Android development, you can find topics on this subject in the Google documentation for Android https://developer.android.com/training/efficient-downloads/efficient-network-access 

If you still have trouble, I recommend posting it on [StackOverflow](https://stackoverflow.com) so that you can get some help from the development community.
